= Index

  * Cairo
  * Cairo::ANTIALIAS_DEFAULT
  * Cairo::ANTIALIAS_GRAY
  * Cairo::ANTIALIAS_NONE
  * Cairo::ANTIALIAS_SUBPIXEL
  * Cairo::BINDINGS_VERSION
  * Cairo::BUILD_VERSION
  * Cairo::CONTENT_ALPHA
  * Cairo::CONTENT_COLOR
  * Cairo::CONTENT_COLOR_ALPHA
  * Cairo::EXTEND_NONE
  * Cairo::EXTEND_PAD
  * Cairo::EXTEND_REFLECT
  * Cairo::EXTEND_REPEAT
  * Cairo::FILL_RULE_EVEN_ODD
  * Cairo::FILL_RULE_WINDING
  * Cairo::FILTER_BEST
  * Cairo::FILTER_BILINEAR
  * Cairo::FILTER_FAST
  * Cairo::FILTER_GAUSSIAN
  * Cairo::FILTER_GOOD
  * Cairo::FILTER_NEAREST
  * Cairo::FONT_SLANT_ITALIC
  * Cairo::FONT_SLANT_NORMAL
  * Cairo::FONT_SLANT_OBLIQUE
  * Cairo::FONT_WEIGHT_BOLD
  * Cairo::FONT_WEIGHT_NORMAL
  * Cairo::FORMAT_A1
  * Cairo::FORMAT_A8
  * Cairo::FORMAT_ARGB32
  * Cairo::FORMAT_RGB24
  * Cairo::HINT_METRICS_DEFAULT
  * Cairo::HINT_METRICS_OFF
  * Cairo::HINT_METRICS_ON
  * Cairo::HINT_STYLE_DEFAULT
  * Cairo::HINT_STYLE_FULL
  * Cairo::HINT_STYLE_MEDIUM
  * Cairo::HINT_STYLE_NONE
  * Cairo::HINT_STYLE_SLIGHT
  * Cairo::LINE_CAP_BUTT
  * Cairo::LINE_CAP_ROUND
  * Cairo::LINE_CAP_SQUARE
  * Cairo::LINE_JOIN_BEVEL
  * Cairo::LINE_JOIN_MITER
  * Cairo::LINE_JOIN_ROUND
  * Cairo::MAJOR_VERSION
  * Cairo::MICRO_VERSION
  * Cairo::MINOR_VERSION
  * Cairo::OPERATOR_ADD
  * Cairo::OPERATOR_ATOP
  * Cairo::OPERATOR_CLEAR
  * Cairo::OPERATOR_DEST
  * Cairo::OPERATOR_DEST_ATOP
  * Cairo::OPERATOR_DEST_IN
  * Cairo::OPERATOR_DEST_OUT
  * Cairo::OPERATOR_DEST_OVER
  * Cairo::OPERATOR_IN
  * Cairo::OPERATOR_OUT
  * Cairo::OPERATOR_OVER
  * Cairo::OPERATOR_SATURATE
  * Cairo::OPERATOR_SOURCE
  * Cairo::OPERATOR_XOR
  * Cairo::PATH_CLOSE_PATH
  * Cairo::PATH_CURVE_TO
  * Cairo::PATH_LINE_TO
  * Cairo::PATH_MOVE_TO
  * Cairo::SUBPIXEL_ORDER_BGR
  * Cairo::SUBPIXEL_ORDER_DEFAULT
  * Cairo::SUBPIXEL_ORDER_RGB
  * Cairo::SUBPIXEL_ORDER_VBGR
  * Cairo::SUBPIXEL_ORDER_VRGB
  * Cairo::SVG_VERSION_1_1
  * Cairo::SVG_VERSION_1_2
  * Cairo::TEXT_CLUSTER_FLAG_BACKWARD
  * Cairo::VERSION
  * Cairo.bindings_version
  * Cairo.exit_application
  * Cairo.normalize_const_name
  * Cairo.satisfied_version?
  * Cairo::Antialias
  * Cairo::Antialias::DEFAULT
  * Cairo::Antialias::GRAY
  * Cairo::Antialias::NONE
  * Cairo::Antialias::SUBPIXEL
  * Cairo::ClipNotRepresentableError
  * Cairo::Color
  * Cairo::Color::ALICE_BLUE
  * Cairo::Color::ALIZARIN_CRIMSON
  * Cairo::Color::AMARANTH
  * Cairo::Color::AMBER
  * Cairo::Color::AMETHYST
  * Cairo::Color::APRICOT
  * Cairo::Color::AQUA
  * Cairo::Color::AQUAMARINE
  * Cairo::Color::ASPARAGUS
  * Cairo::Color::AZURE
  * Cairo::Color::BEIGE
  * Cairo::Color::BISTRE
  * Cairo::Color::BLACK
  * Cairo::Color::BLAZE_ORANGE
  * Cairo::Color::BLUE
  * Cairo::Color::BONDI_BLUE
  * Cairo::Color::BRIGHT_GREEN
  * Cairo::Color::BRIGHT_TURQUOISE
  * Cairo::Color::BROWN
  * Cairo::Color::BUFF
  * Cairo::Color::BURGUNDY
  * Cairo::Color::BURNT_ORANGE
  * Cairo::Color::BURNT_SIENNA
  * Cairo::Color::BURNT_UMBER
  * Cairo::Color::CAMOUFLAGE_GREEN
  * Cairo::Color::CARDINAL
  * Cairo::Color::CARMINE
  * Cairo::Color::CARNATION
  * Cairo::Color::CARROT_ORANGE
  * Cairo::Color::CELADON
  * Cairo::Color::CERISE
  * Cairo::Color::CERULEAN
  * Cairo::Color::CERULEAN_BLUE
  * Cairo::Color::CHARTREUSE
  * Cairo::Color::CHARTREUSE_YELLOW
  * Cairo::Color::CHESTNUT
  * Cairo::Color::CHOCOLATE
  * Cairo::Color::CINNAMON
  * Cairo::Color::COBALT
  * Cairo::Color::COPPER
  * Cairo::Color::COPPER_ROSE
  * Cairo::Color::CORAL
  * Cairo::Color::CORAL_RED
  * Cairo::Color::CORN
  * Cairo::Color::CORNFLOWER_BLUE
  * Cairo::Color::CREAM
  * Cairo::Color::CRIMSON
  * Cairo::Color::CYAN
  * Cairo::Color::DARK_BLUE
  * Cairo::Color::DARK_POWDER_BLUE
  * Cairo::Color::DENIM
  * Cairo::Color::DODGER_BLUE
  * Cairo::Color::EGGPLANT
  * Cairo::Color::EMERALD
  * Cairo::Color::FALU_RED
  * Cairo::Color::FERN_GREEN
  * Cairo::Color::FLAX
  * Cairo::Color::FOREST_GREEN
  * Cairo::Color::FRENCH_ROSE
  * Cairo::Color::FUCHSIA
  * Cairo::Color::GAMBOGE
  * Cairo::Color::GOLD
  * Cairo::Color::GOLDENROD
  * Cairo::Color::GRAY
  * Cairo::Color::GRAY_ASPARAGUS
  * Cairo::Color::GREEN
  * Cairo::Color::GREEN_YELLOW
  * Cairo::Color::HARLEQUIN
  * Cairo::Color::HELIOTROPE
  * Cairo::Color::HEX_RE
  * Cairo::Color::HOLLYWOOD_CERISE
  * Cairo::Color::HOT_MAGENTA
  * Cairo::Color::HOT_PINK
  * Cairo::Color::INDIGO
  * Cairo::Color::INTERNATIONAL_KLEIN_BLUE
  * Cairo::Color::INTERNATIONAL_ORANGE
  * Cairo::Color::IVORY
  * Cairo::Color::JADE
  * Cairo::Color::KHAKI
  * Cairo::Color::KHAKI_X11
  * Cairo::Color::LAVENDER
  * Cairo::Color::LAVENDER_BLUE
  * Cairo::Color::LAVENDER_BLUSH
  * Cairo::Color::LAVENDER_GRAY
  * Cairo::Color::LAVENDER_PINK
  * Cairo::Color::LAVENDER_ROSE
  * Cairo::Color::LEMON
  * Cairo::Color::LEMON_CHIFFON
  * Cairo::Color::LILAC
  * Cairo::Color::LIME
  * Cairo::Color::LINEN
  * Cairo::Color::MAGENTA
  * Cairo::Color::MALACHITE
  * Cairo::Color::MAROON
  * Cairo::Color::MAUVE
  * Cairo::Color::MEDIUM_CARMINE
  * Cairo::Color::MEDIUM_LAVENDER
  * Cairo::Color::MEDIUM_PURPLE
  * Cairo::Color::MIDNIGHT_BLUE
  * Cairo::Color::MINT_GREEN
  * Cairo::Color::MOSS_GREEN
  * Cairo::Color::MOUNTBATTEN_PINK
  * Cairo::Color::MUSTARD
  * Cairo::Color::NAVAJO_WHITE
  * Cairo::Color::NAVY_BLUE
  * Cairo::Color::OCHRE
  * Cairo::Color::OLD_GOLD
  * Cairo::Color::OLD_LACE
  * Cairo::Color::OLD_LAVENDER
  * Cairo::Color::OLD_ROSE
  * Cairo::Color::OLIVE
  * Cairo::Color::OLIVE_DRAB
  * Cairo::Color::ORANGE
  * Cairo::Color::ORANGE_COLOR_WHEEL
  * Cairo::Color::ORANGE_PEEL
  * Cairo::Color::ORANGE_WEB
  * Cairo::Color::ORCHID
  * Cairo::Color::PAPAYA_WHIP
  * Cairo::Color::PASTEL_GREEN
  * Cairo::Color::PASTEL_PINK
  * Cairo::Color::PEACH
  * Cairo::Color::PEACH_ORANGE
  * Cairo::Color::PEACH_YELLOW
  * Cairo::Color::PEAR
  * Cairo::Color::PERIWINKLE
  * Cairo::Color::PERSIAN_BLUE
  * Cairo::Color::PERSIAN_GREEN
  * Cairo::Color::PERSIAN_INDIGO
  * Cairo::Color::PERSIAN_PINK
  * Cairo::Color::PERSIAN_RED
  * Cairo::Color::PERSIAN_ROSE
  * Cairo::Color::PINE_GREEN
  * Cairo::Color::PINK
  * Cairo::Color::PINK_ORANGE
  * Cairo::Color::POMEGRANATE
  * Cairo::Color::POWDER_BLUE_WEB
  * Cairo::Color::PRUSSIAN_BLUE
  * Cairo::Color::PUCE
  * Cairo::Color::PUMPKIN
  * Cairo::Color::PURPLE
  * Cairo::Color::RAW_UMBER
  * Cairo::Color::RED
  * Cairo::Color::RED_VIOLET
  * Cairo::Color::ROBIN_EGG_BLUE
  * Cairo::Color::ROSE
  * Cairo::Color::ROYAL_BLUE
  * Cairo::Color::RUSSET
  * Cairo::Color::RUST
  * Cairo::Color::SAFETY_ORANGE
  * Cairo::Color::SAFFRON
  * Cairo::Color::SALMON
  * Cairo::Color::SANDY_BROWN
  * Cairo::Color::SANGRIA
  * Cairo::Color::SAPPHIRE
  * Cairo::Color::SCARLET
  * Cairo::Color::SCHOOL_BUS_YELLOW
  * Cairo::Color::SEASHELL
  * Cairo::Color::SEA_GREEN
  * Cairo::Color::SELECTIVE_YELLOW
  * Cairo::Color::SEPIA
  * Cairo::Color::SHOCKING_PINK
  * Cairo::Color::SILVER
  * Cairo::Color::SLATE_GRAY
  * Cairo::Color::SMALT
  * Cairo::Color::SPRING_GREEN
  * Cairo::Color::STEEL_BLUE
  * Cairo::Color::SWAMP_GREEN
  * Cairo::Color::TAN
  * Cairo::Color::TANGERINE
  * Cairo::Color::TAUPE
  * Cairo::Color::TAWNY
  * Cairo::Color::TEAL
  * Cairo::Color::TEA_GREEN
  * Cairo::Color::TENNE
  * Cairo::Color::TERRA_COTTA
  * Cairo::Color::THISTLE
  * Cairo::Color::TURQUOISE
  * Cairo::Color::ULTRAMARINE
  * Cairo::Color::VERMILION
  * Cairo::Color::VIOLET
  * Cairo::Color::VIOLET_EGGPLANT
  * Cairo::Color::VIRIDIAN
  * Cairo::Color::WHEAT
  * Cairo::Color::WHITE
  * Cairo::Color::WISTERIA
  * Cairo::Color::YELLOW
  * Cairo::Color::ZINNWALDITE
  * Cairo::Color.parse
  * Cairo::Color.parse_hex_color
  * Cairo::Color::Base
  * Cairo::Color::Base.new
  * Cairo::Color::Base#a
  * Cairo::Color::Base#a=
  * Cairo::Color::Base#alpha
  * Cairo::Color::Base#alpha=
  * Cairo::Color::CMYK
  * Cairo::Color::CMYK.new
  * Cairo::Color::CMYK#c
  * Cairo::Color::CMYK#c=
  * Cairo::Color::CMYK#cyan
  * Cairo::Color::CMYK#cyan=
  * Cairo::Color::CMYK#k
  * Cairo::Color::CMYK#k=
  * Cairo::Color::CMYK#key_plate
  * Cairo::Color::CMYK#key_plate=
  * Cairo::Color::CMYK#m
  * Cairo::Color::CMYK#m=
  * Cairo::Color::CMYK#magenta
  * Cairo::Color::CMYK#magenta=
  * Cairo::Color::CMYK#to_a
  * Cairo::Color::CMYK#to_ary
  * Cairo::Color::CMYK#to_cmyk
  * Cairo::Color::CMYK#to_hsv
  * Cairo::Color::CMYK#to_rgb
  * Cairo::Color::CMYK#y
  * Cairo::Color::CMYK#y=
  * Cairo::Color::CMYK#yellow
  * Cairo::Color::CMYK#yellow=
  * Cairo::Color::HSV
  * Cairo::Color::HSV.new
  * Cairo::Color::HSV#h
  * Cairo::Color::HSV#h=
  * Cairo::Color::HSV#hue
  * Cairo::Color::HSV#hue=
  * Cairo::Color::HSV#s
  * Cairo::Color::HSV#s=
  * Cairo::Color::HSV#saturation
  * Cairo::Color::HSV#saturation=
  * Cairo::Color::HSV#to_a
  * Cairo::Color::HSV#to_ary
  * Cairo::Color::HSV#to_cmyk
  * Cairo::Color::HSV#to_hsv
  * Cairo::Color::HSV#to_rgb
  * Cairo::Color::HSV#v
  * Cairo::Color::HSV#v=
  * Cairo::Color::HSV#value
  * Cairo::Color::HSV#value=
  * Cairo::Color::RGB
  * Cairo::Color::RGB.new
  * Cairo::Color::RGB#b
  * Cairo::Color::RGB#b=
  * Cairo::Color::RGB#blue
  * Cairo::Color::RGB#blue=
  * Cairo::Color::RGB#g
  * Cairo::Color::RGB#g=
  * Cairo::Color::RGB#green
  * Cairo::Color::RGB#green=
  * Cairo::Color::RGB#r
  * Cairo::Color::RGB#r=
  * Cairo::Color::RGB#red
  * Cairo::Color::RGB#red=
  * Cairo::Color::RGB#to_a
  * Cairo::Color::RGB#to_ary
  * Cairo::Color::RGB#to_cmyk
  * Cairo::Color::RGB#to_hsv
  * Cairo::Color::RGB#to_rgb
  * Cairo::Color::RGB#to_s
  * Cairo::Color::X11
  * Cairo::Color::X11::ALICE_BLUE
  * Cairo::Color::X11::ANTIQUE_WHITE
  * Cairo::Color::X11::AQUA
  * Cairo::Color::X11::AQUAMARINE
  * Cairo::Color::X11::AZURE
  * Cairo::Color::X11::BEIGE
  * Cairo::Color::X11::BISQUE
  * Cairo::Color::X11::BLACK
  * Cairo::Color::X11::BLANCHED_ALMOND
  * Cairo::Color::X11::BLUE
  * Cairo::Color::X11::BLUE_VIOLET
  * Cairo::Color::X11::BROWN
  * Cairo::Color::X11::BURLY_WOOD
  * Cairo::Color::X11::CADET_BLUE
  * Cairo::Color::X11::CHARTREUSE
  * Cairo::Color::X11::CHOCOLATE
  * Cairo::Color::X11::CORAL
  * Cairo::Color::X11::CORNFLOWER_BLUE
  * Cairo::Color::X11::CORNSILK
  * Cairo::Color::X11::CRIMSON
  * Cairo::Color::X11::CYAN
  * Cairo::Color::X11::DARK_BLUE
  * Cairo::Color::X11::DARK_CYAN
  * Cairo::Color::X11::DARK_GOLDENROD
  * Cairo::Color::X11::DARK_GRAY
  * Cairo::Color::X11::DARK_GREEN
  * Cairo::Color::X11::DARK_KHAKI
  * Cairo::Color::X11::DARK_MAGENTA
  * Cairo::Color::X11::DARK_OLIVE_GREEN
  * Cairo::Color::X11::DARK_ORANGE
  * Cairo::Color::X11::DARK_ORCHID
  * Cairo::Color::X11::DARK_RED
  * Cairo::Color::X11::DARK_SALMON
  * Cairo::Color::X11::DARK_SEA_GREEN
  * Cairo::Color::X11::DARK_SLATE_BLUE
  * Cairo::Color::X11::DARK_SLATE_GRAY
  * Cairo::Color::X11::DARK_TURQUOISE
  * Cairo::Color::X11::DARK_VIOLET
  * Cairo::Color::X11::DEEP_PINK
  * Cairo::Color::X11::DEEP_SKY_BLUE
  * Cairo::Color::X11::DIM_GRAY
  * Cairo::Color::X11::DODGER_BLUE
  * Cairo::Color::X11::FIRE_BRICK
  * Cairo::Color::X11::FLORAL_WHITE
  * Cairo::Color::X11::FOREST_GREEN
  * Cairo::Color::X11::FUCHSIA
  * Cairo::Color::X11::GAINSBORO
  * Cairo::Color::X11::GHOST_WHITE
  * Cairo::Color::X11::GOLD
  * Cairo::Color::X11::GOLDENROD
  * Cairo::Color::X11::GRAY
  * Cairo::Color::X11::GREEN
  * Cairo::Color::X11::GREEN_YELLOW
  * Cairo::Color::X11::HONEYDEW
  * Cairo::Color::X11::HOT_PINK
  * Cairo::Color::X11::INDIAN_RED
  * Cairo::Color::X11::INDIGO
  * Cairo::Color::X11::IVORY
  * Cairo::Color::X11::KHAKI
  * Cairo::Color::X11::LAVENDER
  * Cairo::Color::X11::LAVENDER_BLUSH
  * Cairo::Color::X11::LAWN_GREEN
  * Cairo::Color::X11::LEMON_CHIFFON
  * Cairo::Color::X11::LIGHT_BLUE
  * Cairo::Color::X11::LIGHT_CORAL
  * Cairo::Color::X11::LIGHT_CYAN
  * Cairo::Color::X11::LIGHT_GOLDENROD_YELLOW
  * Cairo::Color::X11::LIGHT_GREEN
  * Cairo::Color::X11::LIGHT_GREY
  * Cairo::Color::X11::LIGHT_PINK
  * Cairo::Color::X11::LIGHT_SALMON
  * Cairo::Color::X11::LIGHT_SEA_GREEN
  * Cairo::Color::X11::LIGHT_SKY_BLUE
  * Cairo::Color::X11::LIGHT_SLATE_GRAY
  * Cairo::Color::X11::LIGHT_STEEL_BLUE
  * Cairo::Color::X11::LIGHT_YELLOW
  * Cairo::Color::X11::LIME
  * Cairo::Color::X11::LIME_GREEN
  * Cairo::Color::X11::LINEN
  * Cairo::Color::X11::MAGENTA
  * Cairo::Color::X11::MAROON
  * Cairo::Color::X11::MEDIUM_AQUAMARINE
  * Cairo::Color::X11::MEDIUM_BLUE
  * Cairo::Color::X11::MEDIUM_ORCHID
  * Cairo::Color::X11::MEDIUM_PURPLE
  * Cairo::Color::X11::MEDIUM_SEA_GREEN
  * Cairo::Color::X11::MEDIUM_SLATE_BLUE
  * Cairo::Color::X11::MEDIUM_SPRING_GREEN
  * Cairo::Color::X11::MEDIUM_TURQUOISE
  * Cairo::Color::X11::MEDIUM_VIOLET_RED
  * Cairo::Color::X11::MIDNIGHT_BLUE
  * Cairo::Color::X11::MINT_CREAM
  * Cairo::Color::X11::MISTY_ROSE
  * Cairo::Color::X11::MOCCASIN
  * Cairo::Color::X11::NAVAJO_WHITE
  * Cairo::Color::X11::OLD_LACE
  * Cairo::Color::X11::OLIVE
  * Cairo::Color::X11::OLIVE_DRAB
  * Cairo::Color::X11::ORANGE
  * Cairo::Color::X11::ORANGE_RED
  * Cairo::Color::X11::ORCHID
  * Cairo::Color::X11::PALE_GOLDENROD
  * Cairo::Color::X11::PALE_GREEN
  * Cairo::Color::X11::PALE_TURQUOISE
  * Cairo::Color::X11::PALE_VIOLET_RED
  * Cairo::Color::X11::PAPAYA_WHIP
  * Cairo::Color::X11::PEACH_PUFF
  * Cairo::Color::X11::PERU
  * Cairo::Color::X11::PINK
  * Cairo::Color::X11::PLUM
  * Cairo::Color::X11::POWDER_BLUE
  * Cairo::Color::X11::PURPLE
  * Cairo::Color::X11::RED
  * Cairo::Color::X11::ROSY_BROWN
  * Cairo::Color::X11::ROYAL_BLUE
  * Cairo::Color::X11::SADDLE_BROWN
  * Cairo::Color::X11::SALMON
  * Cairo::Color::X11::SANDY_BROWN
  * Cairo::Color::X11::SEASHELL
  * Cairo::Color::X11::SEA_GREEN
  * Cairo::Color::X11::SIENNA
  * Cairo::Color::X11::SILVER
  * Cairo::Color::X11::SKY_BLUE
  * Cairo::Color::X11::SLATE_BLUE
  * Cairo::Color::X11::SLATE_GRAY
  * Cairo::Color::X11::SNOW
  * Cairo::Color::X11::SPRING_GREEN
  * Cairo::Color::X11::STEEL_BLUE
  * Cairo::Color::X11::TAN
  * Cairo::Color::X11::TEAL
  * Cairo::Color::X11::THISTLE
  * Cairo::Color::X11::TOMATO
  * Cairo::Color::X11::TURQUOISE
  * Cairo::Color::X11::VIOLET
  * Cairo::Color::X11::WHEAT
  * Cairo::Color::X11::WHITE
  * Cairo::Color::X11::WHITE_SMOKE
  * Cairo::Color::X11::YELLOW
  * Cairo::Color::X11::YELLOW_GREEN
  * Cairo::Content
  * Cairo::Content::ALPHA
  * Cairo::Content::COLOR
  * Cairo::Content::COLOR_ALPHA
  * Cairo::Context
  * Cairo::Context.new
  * Cairo::Context#antialias
  * Cairo::Context#antialias=
  * Cairo::Context#append_path
  * Cairo::Context#arc
  * Cairo::Context#arc_negative
  * Cairo::Context#circle
  * Cairo::Context#clip
  * Cairo::Context#clip_extents
  * Cairo::Context#clip_preserve
  * Cairo::Context#clip_rectangle_list
  * Cairo::Context#close_path
  * Cairo::Context#copy_page
  * Cairo::Context#copy_path
  * Cairo::Context#copy_path_flat
  * Cairo::Context#current_point
  * Cairo::Context#curve_to
  * Cairo::Context#dash
  * Cairo::Context#dash_count
  * Cairo::Context#destroy
  * Cairo::Context#device_to_user
  * Cairo::Context#device_to_user_distance
  * Cairo::Context#fill
  * Cairo::Context#fill_extents
  * Cairo::Context#fill_preserve
  * Cairo::Context#fill_rule
  * Cairo::Context#fill_rule=
  * Cairo::Context#font_extents
  * Cairo::Context#font_face
  * Cairo::Context#font_face=
  * Cairo::Context#font_matrix
  * Cairo::Context#font_matrix=
  * Cairo::Context#font_options
  * Cairo::Context#font_options=
  * Cairo::Context#font_size=
  * Cairo::Context#glyph_extents
  * Cairo::Context#glyph_path
  * Cairo::Context#group_target
  * Cairo::Context#has_current_point?
  * Cairo::Context#have_current_point?
  * Cairo::Context#identity_matrix
  * Cairo::Context#in_fill?
  * Cairo::Context#in_stroke?
  * Cairo::Context#line_cap
  * Cairo::Context#line_cap=
  * Cairo::Context#line_join
  * Cairo::Context#line_join=
  * Cairo::Context#line_to
  * Cairo::Context#line_width
  * Cairo::Context#line_width=
  * Cairo::Context#map_path_onto
  * Cairo::Context#mask
  * Cairo::Context#matrix
  * Cairo::Context#matrix=
  * Cairo::Context#miter_limit
  * Cairo::Context#miter_limit=
  * Cairo::Context#move_to
  * Cairo::Context#new_path
  * Cairo::Context#new_sub_path
  * Cairo::Context#operator
  * Cairo::Context#operator=
  * Cairo::Context#paint
  * Cairo::Context#path_extents
  * Cairo::Context#pop_group
  * Cairo::Context#pop_group_to_source
  * Cairo::Context#pseudo_blur
  * Cairo::Context#push_group
  * Cairo::Context#rectangle
  * Cairo::Context#rel_curve_to
  * Cairo::Context#rel_line_to
  * Cairo::Context#rel_move_to
  * Cairo::Context#reset_clip
  * Cairo::Context#restore
  * Cairo::Context#rotate
  * Cairo::Context#rounded_rectangle
  * Cairo::Context#save
  * Cairo::Context#scale
  * Cairo::Context#scaled_font
  * Cairo::Context#scaled_font=
  * Cairo::Context#select_font_face
  * Cairo::Context#set_antialias
  * Cairo::Context#set_dash
  * Cairo::Context#set_fill_rule
  * Cairo::Context#set_font_face
  * Cairo::Context#set_font_matrix
  * Cairo::Context#set_font_options
  * Cairo::Context#set_font_size
  * Cairo::Context#set_line_cap
  * Cairo::Context#set_line_join
  * Cairo::Context#set_line_width
  * Cairo::Context#set_matrix
  * Cairo::Context#set_miter_limit
  * Cairo::Context#set_operator
  * Cairo::Context#set_scaled_font
  * Cairo::Context#set_source
  * Cairo::Context#set_source_color
  * Cairo::Context#set_source_rgb
  * Cairo::Context#set_source_rgba
  * Cairo::Context#set_tolerance
  * Cairo::Context#show_glyphs
  * Cairo::Context#show_page
  * Cairo::Context#show_text
  * Cairo::Context#show_text_glyphs
  * Cairo::Context#source
  * Cairo::Context#stroke
  * Cairo::Context#stroke_extents
  * Cairo::Context#stroke_preserve
  * Cairo::Context#target
  * Cairo::Context#text_extents
  * Cairo::Context#text_path
  * Cairo::Context#tolerance
  * Cairo::Context#tolerance=
  * Cairo::Context#transform
  * Cairo::Context#transform_path
  * Cairo::Context#translate
  * Cairo::Context#triangle
  * Cairo::Context#user_to_device
  * Cairo::Context#user_to_device_distance
  * Cairo::Context::Blur
  * Cairo::Context::Blur#pseudo_blur
  * Cairo::Context::Circle
  * Cairo::Context::Circle#circle
  * Cairo::Context::Color
  * Cairo::Context::Color#set_source_color
  * Cairo::Context::Path
  * Cairo::Context::Path#map_path_onto
  * Cairo::Context::Path#transform_path
  * Cairo::Context::Rectangle
  * Cairo::Context::Rectangle#rounded_rectangle
  * Cairo::Context::Triangle
  * Cairo::Context::Triangle#triangle
  * Cairo::Error
  * Cairo::Extend
  * Cairo::Extend::NONE
  * Cairo::Extend::PAD
  * Cairo::Extend::REFLECT
  * Cairo::Extend::REPEAT
  * Cairo::FileNotFound
  * Cairo::FillRule
  * Cairo::FillRule::EVEN_ODD
  * Cairo::FillRule::WINDING
  * Cairo::Filter
  * Cairo::Filter::BEST
  * Cairo::Filter::BILINEAR
  * Cairo::Filter::FAST
  * Cairo::Filter::GAUSSIAN
  * Cairo::Filter::GOOD
  * Cairo::Filter::NEAREST
  * Cairo::FontExtents
  * Cairo::FontExtents.new
  * Cairo::FontExtents#ascent
  * Cairo::FontExtents#ascent=
  * Cairo::FontExtents#descent
  * Cairo::FontExtents#descent=
  * Cairo::FontExtents#height
  * Cairo::FontExtents#height=
  * Cairo::FontExtents#max_x_advance
  * Cairo::FontExtents#max_x_advance=
  * Cairo::FontExtents#max_y_advance
  * Cairo::FontExtents#max_y_advance=
  * Cairo::FontExtents#set_ascent
  * Cairo::FontExtents#set_descent
  * Cairo::FontExtents#set_height
  * Cairo::FontExtents#set_max_x_advance
  * Cairo::FontExtents#set_max_y_advance
  * Cairo::FontExtents#to_s
  * Cairo::FontFace
  * Cairo::FontOptions
  * Cairo::FontOptions.new
  * Cairo::FontOptions#antialias
  * Cairo::FontOptions#antialias=
  * Cairo::FontOptions#dup
  * Cairo::FontOptions#eql?
  * Cairo::FontOptions#hash
  * Cairo::FontOptions#hint_metrics
  * Cairo::FontOptions#hint_metrics=
  * Cairo::FontOptions#hint_style
  * Cairo::FontOptions#hint_style=
  * Cairo::FontOptions#merge
  * Cairo::FontOptions#merge!
  * Cairo::FontOptions#set_antialias
  * Cairo::FontOptions#set_hint_metrics
  * Cairo::FontOptions#set_hint_style
  * Cairo::FontOptions#set_subpixel_order
  * Cairo::FontOptions#subpixel_order
  * Cairo::FontOptions#subpixel_order=
  * Cairo::FontOptions#update
  * Cairo::FontSlant
  * Cairo::FontSlant::ITALIC
  * Cairo::FontSlant::NORMAL
  * Cairo::FontSlant::OBLIQUE
  * Cairo::FontTypeMismatch
  * Cairo::FontWeight
  * Cairo::FontWeight::BOLD
  * Cairo::FontWeight::NORMAL
  * Cairo::Format
  * Cairo::Format::A1
  * Cairo::Format::A8
  * Cairo::Format::ARGB32
  * Cairo::Format::RGB24
  * Cairo::Format.stride_for_width
  * Cairo::Glyph
  * Cairo::Glyph.new
  * Cairo::Glyph#index
  * Cairo::Glyph#index=
  * Cairo::Glyph#set_index
  * Cairo::Glyph#set_x
  * Cairo::Glyph#set_y
  * Cairo::Glyph#to_s
  * Cairo::Glyph#x
  * Cairo::Glyph#x=
  * Cairo::Glyph#y
  * Cairo::Glyph#y=
  * Cairo::GradientPattern
  * Cairo::GradientPattern#add_color_stop
  * Cairo::GradientPattern#add_color_stop_rgb
  * Cairo::GradientPattern#add_color_stop_rgba
  * Cairo::GradientPattern#color_stop_count
  * Cairo::GradientPattern#get_color_stop_color
  * Cairo::GradientPattern#get_color_stop_rgba
  * Cairo::HintMetrics
  * Cairo::HintMetrics::DEFAULT
  * Cairo::HintMetrics::OFF
  * Cairo::HintMetrics::ON
  * Cairo::HintStyle
  * Cairo::HintStyle::DEFAULT
  * Cairo::HintStyle::FULL
  * Cairo::HintStyle::MEDIUM
  * Cairo::HintStyle::NONE
  * Cairo::HintStyle::SLIGHT
  * Cairo::ImageSurface
  * Cairo::ImageSurface.from_png
  * Cairo::ImageSurface.new
  * Cairo::ImageSurface#data
  * Cairo::ImageSurface#format
  * Cairo::ImageSurface#height
  * Cairo::ImageSurface#stride
  * Cairo::ImageSurface#width
  * Cairo::InvalidClusters
  * Cairo::InvalidContentError
  * Cairo::InvalidDashError
  * Cairo::InvalidDscCommentError
  * Cairo::InvalidFormatError
  * Cairo::InvalidIndexError
  * Cairo::InvalidMatrixError
  * Cairo::InvalidPathDataError
  * Cairo::InvalidPopGroupError
  * Cairo::InvalidRestoreError
  * Cairo::InvalidSlant
  * Cairo::InvalidStatusError
  * Cairo::InvalidStrideError
  * Cairo::InvalidStringError
  * Cairo::InvalidVisualError
  * Cairo::InvalidWeight
  * Cairo::LineCap
  * Cairo::LineCap::BUTT
  * Cairo::LineCap::ROUND
  * Cairo::LineCap::SQUARE
  * Cairo::LineJoin
  * Cairo::LineJoin::BEVEL
  * Cairo::LineJoin::MITER
  * Cairo::LineJoin::ROUND
  * Cairo::LinearPattern
  * Cairo::LinearPattern.new
  * Cairo::LinearPattern#points
  * Cairo::Matrix
  * Cairo::Matrix.identity
  * Cairo::Matrix.new
  * Cairo::Matrix.rotate
  * Cairo::Matrix.scale
  * Cairo::Matrix.translate
  * Cairo::Matrix#*
  * Cairo::Matrix#==
  * Cairo::Matrix#clone
  * Cairo::Matrix#dup
  * Cairo::Matrix#identity!
  * Cairo::Matrix#invert
  * Cairo::Matrix#invert!
  * Cairo::Matrix#multiply
  * Cairo::Matrix#multiply!
  * Cairo::Matrix#rotate
  * Cairo::Matrix#rotate!
  * Cairo::Matrix#scale
  * Cairo::Matrix#scale!
  * Cairo::Matrix#set
  * Cairo::Matrix#set_x0
  * Cairo::Matrix#set_xx
  * Cairo::Matrix#set_xy
  * Cairo::Matrix#set_y0
  * Cairo::Matrix#set_yx
  * Cairo::Matrix#set_yy
  * Cairo::Matrix#to_a
  * Cairo::Matrix#to_s
  * Cairo::Matrix#transform_distance
  * Cairo::Matrix#transform_point
  * Cairo::Matrix#translate
  * Cairo::Matrix#translate!
  * Cairo::Matrix#x0
  * Cairo::Matrix#x0=
  * Cairo::Matrix#xx
  * Cairo::Matrix#xx=
  * Cairo::Matrix#xy
  * Cairo::Matrix#xy=
  * Cairo::Matrix#y0
  * Cairo::Matrix#y0=
  * Cairo::Matrix#yx
  * Cairo::Matrix#yx=
  * Cairo::Matrix#yy
  * Cairo::Matrix#yy=
  * Cairo::NegativeCount
  * Cairo::NoCurrentPointError
  * Cairo::NullPointerError
  * Cairo::Operator
  * Cairo::Operator::ADD
  * Cairo::Operator::ATOP
  * Cairo::Operator::CLEAR
  * Cairo::Operator::DEST
  * Cairo::Operator::DEST_ATOP
  * Cairo::Operator::DEST_IN
  * Cairo::Operator::DEST_OUT
  * Cairo::Operator::DEST_OVER
  * Cairo::Operator::IN
  * Cairo::Operator::OUT
  * Cairo::Operator::OVER
  * Cairo::Operator::SATURATE
  * Cairo::Operator::SOURCE
  * Cairo::Operator::XOR
  * Cairo::PDFSurface
  * Cairo::PDFSurface.new
  * Cairo::PDFSurface#set_size
  * Cairo::PSLevel
  * Cairo::PSLevel::LEVEL_2
  * Cairo::PSLevel::LEVEL_3
  * Cairo::PSLevel.list
  * Cairo::PSLevel.names
  * Cairo::PSSurface
  * Cairo::PSSurface.new
  * Cairo::PSSurface#dsc_begin_page_setup
  * Cairo::PSSurface#dsc_begin_setup
  * Cairo::PSSurface#dsc_comment
  * Cairo::PSSurface#eps=
  * Cairo::PSSurface#eps?
  * Cairo::PSSurface#restrict_to_level
  * Cairo::PSSurface#set_eps
  * Cairo::PSSurface#set_size
  * Cairo::Paper
  * Cairo::Paper::A0
  * Cairo::Paper::A0_LANDSCAPE
  * Cairo::Paper::A1
  * Cairo::Paper::A10
  * Cairo::Paper::A10_LANDSCAPE
  * Cairo::Paper::A1_LANDSCAPE
  * Cairo::Paper::A2
  * Cairo::Paper::A2_LANDSCAPE
  * Cairo::Paper::A3
  * Cairo::Paper::A3_LANDSCAPE
  * Cairo::Paper::A4
  * Cairo::Paper::A4_LANDSCAPE
  * Cairo::Paper::A5
  * Cairo::Paper::A5_LANDSCAPE
  * Cairo::Paper::A6
  * Cairo::Paper::A6_LANDSCAPE
  * Cairo::Paper::A7
  * Cairo::Paper::A7_LANDSCAPE
  * Cairo::Paper::A8
  * Cairo::Paper::A8_LANDSCAPE
  * Cairo::Paper::A9
  * Cairo::Paper::A9_LANDSCAPE
  * Cairo::Paper::B0
  * Cairo::Paper::B0_LANDSCAPE
  * Cairo::Paper::B1
  * Cairo::Paper::B10
  * Cairo::Paper::B10_LANDSCAPE
  * Cairo::Paper::B1_LANDSCAPE
  * Cairo::Paper::B2
  * Cairo::Paper::B2_LANDSCAPE
  * Cairo::Paper::B3
  * Cairo::Paper::B3_LANDSCAPE
  * Cairo::Paper::B4
  * Cairo::Paper::B4_LANDSCAPE
  * Cairo::Paper::B5
  * Cairo::Paper::B5_LANDSCAPE
  * Cairo::Paper::B6
  * Cairo::Paper::B6_LANDSCAPE
  * Cairo::Paper::B7
  * Cairo::Paper::B7_LANDSCAPE
  * Cairo::Paper::B8
  * Cairo::Paper::B8_LANDSCAPE
  * Cairo::Paper::B9
  * Cairo::Paper::B9_LANDSCAPE
  * Cairo::Paper::JAPANESE_POSTCARD
  * Cairo::Paper::JAPANESE_POSTCARD_LANDSCAPE
  * Cairo::Paper::LEGAL
  * Cairo::Paper::LEGAL_LANDSCAPE
  * Cairo::Paper::LETTER
  * Cairo::Paper::LETTER_LANDSCAPE
  * Cairo::Paper::TABLOID
  * Cairo::Paper::TABLOID_LANDSCAPE
  * Cairo::Paper.default_unit
  * Cairo::Paper.default_unit=
  * Cairo::Paper.new
  * Cairo::Paper.parse
  * Cairo::Paper.register_unit_resolver
  * Cairo::Paper.resolve_unit
  * Cairo::Paper#==
  * Cairo::Paper#height
  * Cairo::Paper#height=
  * Cairo::Paper#name
  * Cairo::Paper#name=
  * Cairo::Paper#size
  * Cairo::Paper#to_s
  * Cairo::Paper#unit
  * Cairo::Paper#unit=
  * Cairo::Paper#width
  * Cairo::Paper#width=
  * Cairo::Paper::ParseError
  * Cairo::Paper::UnknownPaperName
  * Cairo::Paper::UnknownPaperName.new
  * Cairo::Paper::UnknownPaperName#name
  * Cairo::Paper::UnknownUnit
  * Cairo::Paper::UnknownUnit.new
  * Cairo::Paper::UnknownUnit#unit
  * Cairo::Paper::UnrecognizedPaperDescription
  * Cairo::Paper::UnrecognizedPaperDescription.new
  * Cairo::Paper::UnrecognizedPaperDescription#description
  * Cairo::Path
  * Cairo::Path::CLOSE_PATH
  * Cairo::Path::CURVE_TO
  * Cairo::Path::LINE_TO
  * Cairo::Path::MOVE_TO
  * Cairo::Path.new
  * Cairo::Path#[]
  * Cairo::Path#arc
  * Cairo::Path#arc_negative
  * Cairo::Path#circle
  * Cairo::Path#close
  * Cairo::Path#curve_to
  * Cairo::Path#each
  * Cairo::Path#empty?
  * Cairo::Path#length
  * Cairo::Path#line_to
  * Cairo::Path#move_to
  * Cairo::Path#new_path
  * Cairo::Path#new_sub_path
  * Cairo::Path#rectangle
  * Cairo::Path#rel_curve_to
  * Cairo::Path#rel_line_to
  * Cairo::Path#rel_move_to
  * Cairo::Path#rounded_rectangle
  * Cairo::Path#size
  * Cairo::PathClosePath
  * Cairo::PathClosePath.new
  * Cairo::PathCurveTo
  * Cairo::PathCurveTo.new
  * Cairo::PathData
  * Cairo::PathData.new
  * Cairo::PathData#close_path?
  * Cairo::PathData#curve_to?
  * Cairo::PathData#each
  * Cairo::PathData#line_to?
  * Cairo::PathData#move_to?
  * Cairo::PathData#points
  * Cairo::PathData#to_a
  * Cairo::PathData#to_ary
  * Cairo::PathData#type
  * Cairo::PathDataType
  * Cairo::PathDataType::CLOSE_PATH
  * Cairo::PathDataType::CURVE_TO
  * Cairo::PathDataType::LINE_TO
  * Cairo::PathDataType::MOVE_TO
  * Cairo::PathLineTo
  * Cairo::PathLineTo.new
  * Cairo::PathMoveTo
  * Cairo::PathMoveTo.new
  * Cairo::Pattern
  * Cairo::Pattern.new
  * Cairo::Pattern#__extend__
  * Cairo::Pattern#extend
  * Cairo::Pattern#extend=
  * Cairo::Pattern#filter
  * Cairo::Pattern#filter=
  * Cairo::Pattern#matrix
  * Cairo::Pattern#matrix=
  * Cairo::Pattern#set_extend
  * Cairo::Pattern#set_filter
  * Cairo::Pattern#set_matrix
  * Cairo::PatternTypeMismatchError
  * Cairo::Point
  * Cairo::Point.new
  * Cairo::Point#distance
  * Cairo::Point#to_a
  * Cairo::Point#to_ary
  * Cairo::Point#x
  * Cairo::Point#y
  * Cairo::QuartzImageSurface
  * Cairo::QuartzImageSurface.new
  * Cairo::QuartzImageSurface#image
  * Cairo::QuartzSurface
  * Cairo::QuartzSurface.new
  * Cairo::QuartzSurface#cg_context
  * Cairo::RadialPattern
  * Cairo::RadialPattern.new
  * Cairo::RadialPattern#circles
  * Cairo::ReadError
  * Cairo::Rectangle
  * Cairo::Rectangle.new
  * Cairo::Rectangle#height
  * Cairo::Rectangle#height=
  * Cairo::Rectangle#width
  * Cairo::Rectangle#width=
  * Cairo::Rectangle#x
  * Cairo::Rectangle#x=
  * Cairo::Rectangle#y
  * Cairo::Rectangle#y=
  * Cairo::SVGSurface
  * Cairo::SVGSurface::VERSION_1_1
  * Cairo::SVGSurface::VERSION_1_2
  * Cairo::SVGSurface.new
  * Cairo::SVGSurface.version_to_string
  * Cairo::SVGSurface.versions
  * Cairo::SVGSurface.versions_as_string
  * Cairo::SVGSurface#restrict_to_version
  * Cairo::SVGVersion
  * Cairo::SVGVersion::VERSION_1_1
  * Cairo::SVGVersion::VERSION_1_2
  * Cairo::SVGVersion.list
  * Cairo::SVGVersion.names
  * Cairo::ScaledFont
  * Cairo::ScaledFont.new
  * Cairo::ScaledFont#ctm
  * Cairo::ScaledFont#extents
  * Cairo::ScaledFont#font_face
  * Cairo::ScaledFont#font_matrix
  * Cairo::ScaledFont#font_options
  * Cairo::ScaledFont#glyph_extents
  * Cairo::ScaledFont#scale_matrix
  * Cairo::ScaledFont#text_extents
  * Cairo::ScaledFont#text_to_glyphs
  * Cairo::SolidPattern
  * Cairo::SolidPattern.new
  * Cairo::SolidPattern#color
  * Cairo::SolidPattern#rgba
  * Cairo::SubpixelOrder
  * Cairo::SubpixelOrder::BGR
  * Cairo::SubpixelOrder::DEFAULT
  * Cairo::SubpixelOrder::RGB
  * Cairo::SubpixelOrder::VBGR
  * Cairo::SubpixelOrder::VRGB
  * Cairo::Surface
  * Cairo::Surface#clone
  * Cairo::Surface#content
  * Cairo::Surface#copy_page
  * Cairo::Surface#create_similar
  * Cairo::Surface#destroy
  * Cairo::Surface#device_offset
  * Cairo::Surface#dup
  * Cairo::Surface#fallback_resolution
  * Cairo::Surface#finish
  * Cairo::Surface#flush
  * Cairo::Surface#font_options
  * Cairo::Surface#mark_dirty
  * Cairo::Surface#set_device_offset
  * Cairo::Surface#set_fallback_resolution
  * Cairo::Surface#show_page
  * Cairo::Surface#write_to_png
  * Cairo::SurfaceFinishedError
  * Cairo::SurfacePattern
  * Cairo::SurfacePattern.new
  * Cairo::SurfacePattern#surface
  * Cairo::SurfaceTypeMismatchError
  * Cairo::TempFileError
  * Cairo::TextCluster
  * Cairo::TextCluster.new
  * Cairo::TextCluster#num_bytes
  * Cairo::TextCluster#num_bytes=
  * Cairo::TextCluster#num_glyphs
  * Cairo::TextCluster#num_glyphs=
  * Cairo::TextCluster#set_num_bytes
  * Cairo::TextCluster#set_num_glyphs
  * Cairo::TextCluster#to_s
  * Cairo::TextClusterFlag
  * Cairo::TextClusterFlag::BACKWARD
  * Cairo::TextExtents
  * Cairo::TextExtents.new
  * Cairo::TextExtents#height
  * Cairo::TextExtents#height=
  * Cairo::TextExtents#set_height
  * Cairo::TextExtents#set_width
  * Cairo::TextExtents#set_x_advance
  * Cairo::TextExtents#set_x_bearing
  * Cairo::TextExtents#set_y_advance
  * Cairo::TextExtents#set_y_bearing
  * Cairo::TextExtents#to_s
  * Cairo::TextExtents#width
  * Cairo::TextExtents#width=
  * Cairo::TextExtents#x_advance
  * Cairo::TextExtents#x_advance=
  * Cairo::TextExtents#x_bearing
  * Cairo::TextExtents#x_bearing=
  * Cairo::TextExtents#y_advance
  * Cairo::TextExtents#y_advance=
  * Cairo::TextExtents#y_bearing
  * Cairo::TextExtents#y_bearing=
  * Cairo::ToyFontFace
  * Cairo::ToyFontFace.new
  * Cairo::ToyFontFace#family
  * Cairo::ToyFontFace#slant
  * Cairo::ToyFontFace#weight
  * Cairo::UserFontError
  * Cairo::UserFontFace
  * Cairo::UserFontFace.new
  * Cairo::UserFontFace#on_init
  * Cairo::UserFontFace#on_render_glyph
  * Cairo::UserFontFace#on_text_to_glyphs
  * Cairo::UserFontFace#on_unicode_to_glyph
  * Cairo::UserFontFace::TextToGlyphsData
  * Cairo::UserFontFace::TextToGlyphsData.new
  * Cairo::UserFontFace::TextToGlyphsData#cluster_flags
  * Cairo::UserFontFace::TextToGlyphsData#cluster_flags=
  * Cairo::UserFontFace::TextToGlyphsData#clusters
  * Cairo::UserFontFace::TextToGlyphsData#clusters=
  * Cairo::UserFontFace::TextToGlyphsData#glyphs
  * Cairo::UserFontFace::TextToGlyphsData#glyphs=
  * Cairo::UserFontFace::TextToGlyphsData#need_cluster_flags?
  * Cairo::UserFontFace::TextToGlyphsData#need_clusters?
  * Cairo::UserFontFace::TextToGlyphsData#need_glyphs?
  * Cairo::UserFontImmutable
  * Cairo::Win32PrintingSurface
  * Cairo::Win32PrintingSurface.new
  * Cairo::Win32PrintingSurface#hdc
  * Cairo::Win32Surface
  * Cairo::Win32Surface.new
  * Cairo::Win32Surface#hdc
  * Cairo::Win32Surface#image
  * Cairo::WriteError
