= Index

  * ((<Cairo|cairo.rd/module Cairo>))
  * ((<Cairo::ANTIALIAS_DEFAULT|cairo.rd/ANTIALIAS_DEFAULT>))
  * ((<Cairo::ANTIALIAS_GRAY|cairo.rd/ANTIALIAS_GRAY>))
  * ((<Cairo::ANTIALIAS_NONE|cairo.rd/ANTIALIAS_NONE>))
  * ((<Cairo::ANTIALIAS_SUBPIXEL|cairo.rd/ANTIALIAS_SUBPIXEL>))
  * ((<Cairo::BINDINGS_VERSION|cairo.rd/BINDINGS_VERSION>))
  * ((<Cairo::BUILD_VERSION|cairo.rd/BUILD_VERSION>))
  * ((<Cairo::CONTENT_ALPHA|cairo.rd/CONTENT_ALPHA>))
  * ((<Cairo::CONTENT_COLOR|cairo.rd/CONTENT_COLOR>))
  * ((<Cairo::CONTENT_COLOR_ALPHA|cairo.rd/CONTENT_COLOR_ALPHA>))
  * ((<Cairo::EXTEND_NONE|cairo.rd/EXTEND_NONE>))
  * ((<Cairo::EXTEND_PAD|cairo.rd/EXTEND_PAD>))
  * ((<Cairo::EXTEND_REFLECT|cairo.rd/EXTEND_REFLECT>))
  * ((<Cairo::EXTEND_REPEAT|cairo.rd/EXTEND_REPEAT>))
  * ((<Cairo::FILL_RULE_EVEN_ODD|cairo.rd/FILL_RULE_EVEN_ODD>))
  * ((<Cairo::FILL_RULE_WINDING|cairo.rd/FILL_RULE_WINDING>))
  * ((<Cairo::FILTER_BEST|cairo.rd/FILTER_BEST>))
  * ((<Cairo::FILTER_BILINEAR|cairo.rd/FILTER_BILINEAR>))
  * ((<Cairo::FILTER_FAST|cairo.rd/FILTER_FAST>))
  * ((<Cairo::FILTER_GAUSSIAN|cairo.rd/FILTER_GAUSSIAN>))
  * ((<Cairo::FILTER_GOOD|cairo.rd/FILTER_GOOD>))
  * ((<Cairo::FILTER_NEAREST|cairo.rd/FILTER_NEAREST>))
  * ((<Cairo::FONT_SLANT_ITALIC|cairo.rd/FONT_SLANT_ITALIC>))
  * ((<Cairo::FONT_SLANT_NORMAL|cairo.rd/FONT_SLANT_NORMAL>))
  * ((<Cairo::FONT_SLANT_OBLIQUE|cairo.rd/FONT_SLANT_OBLIQUE>))
  * ((<Cairo::FONT_TYPE_ATSUI|cairo.rd/FONT_TYPE_ATSUI>))
  * ((<Cairo::FONT_TYPE_FT|cairo.rd/FONT_TYPE_FT>))
  * ((<Cairo::FONT_TYPE_TOY|cairo.rd/FONT_TYPE_TOY>))
  * ((<Cairo::FONT_TYPE_WIN32|cairo.rd/FONT_TYPE_WIN32>))
  * ((<Cairo::FONT_WEIGHT_BOLD|cairo.rd/FONT_WEIGHT_BOLD>))
  * ((<Cairo::FONT_WEIGHT_NORMAL|cairo.rd/FONT_WEIGHT_NORMAL>))
  * ((<Cairo::FORMAT_A1|cairo.rd/FORMAT_A1>))
  * ((<Cairo::FORMAT_A8|cairo.rd/FORMAT_A8>))
  * ((<Cairo::FORMAT_ARGB32|cairo.rd/FORMAT_ARGB32>))
  * ((<Cairo::FORMAT_RGB16_565|cairo.rd/FORMAT_RGB16_565>))
  * ((<Cairo::FORMAT_RGB24|cairo.rd/FORMAT_RGB24>))
  * ((<Cairo::HINT_METRICS_DEFAULT|cairo.rd/HINT_METRICS_DEFAULT>))
  * ((<Cairo::HINT_METRICS_OFF|cairo.rd/HINT_METRICS_OFF>))
  * ((<Cairo::HINT_METRICS_ON|cairo.rd/HINT_METRICS_ON>))
  * ((<Cairo::HINT_STYLE_DEFAULT|cairo.rd/HINT_STYLE_DEFAULT>))
  * ((<Cairo::HINT_STYLE_FULL|cairo.rd/HINT_STYLE_FULL>))
  * ((<Cairo::HINT_STYLE_MEDIUM|cairo.rd/HINT_STYLE_MEDIUM>))
  * ((<Cairo::HINT_STYLE_NONE|cairo.rd/HINT_STYLE_NONE>))
  * ((<Cairo::HINT_STYLE_SLIGHT|cairo.rd/HINT_STYLE_SLIGHT>))
  * ((<Cairo::LINE_CAP_BUTT|cairo.rd/LINE_CAP_BUTT>))
  * ((<Cairo::LINE_CAP_ROUND|cairo.rd/LINE_CAP_ROUND>))
  * ((<Cairo::LINE_CAP_SQUARE|cairo.rd/LINE_CAP_SQUARE>))
  * ((<Cairo::LINE_JOIN_BEVEL|cairo.rd/LINE_JOIN_BEVEL>))
  * ((<Cairo::LINE_JOIN_MITER|cairo.rd/LINE_JOIN_MITER>))
  * ((<Cairo::LINE_JOIN_ROUND|cairo.rd/LINE_JOIN_ROUND>))
  * ((<Cairo::MAJOR_VERSION|cairo.rd/MAJOR_VERSION>))
  * ((<Cairo::MICRO_VERSION|cairo.rd/MICRO_VERSION>))
  * ((<Cairo::MINOR_VERSION|cairo.rd/MINOR_VERSION>))
  * ((<Cairo::OPERATOR_ADD|cairo.rd/OPERATOR_ADD>))
  * ((<Cairo::OPERATOR_ATOP|cairo.rd/OPERATOR_ATOP>))
  * ((<Cairo::OPERATOR_CLEAR|cairo.rd/OPERATOR_CLEAR>))
  * ((<Cairo::OPERATOR_DEST|cairo.rd/OPERATOR_DEST>))
  * ((<Cairo::OPERATOR_DEST_ATOP|cairo.rd/OPERATOR_DEST_ATOP>))
  * ((<Cairo::OPERATOR_DEST_IN|cairo.rd/OPERATOR_DEST_IN>))
  * ((<Cairo::OPERATOR_DEST_OUT|cairo.rd/OPERATOR_DEST_OUT>))
  * ((<Cairo::OPERATOR_DEST_OVER|cairo.rd/OPERATOR_DEST_OVER>))
  * ((<Cairo::OPERATOR_IN|cairo.rd/OPERATOR_IN>))
  * ((<Cairo::OPERATOR_OUT|cairo.rd/OPERATOR_OUT>))
  * ((<Cairo::OPERATOR_OVER|cairo.rd/OPERATOR_OVER>))
  * ((<Cairo::OPERATOR_SATURATE|cairo.rd/OPERATOR_SATURATE>))
  * ((<Cairo::OPERATOR_SOURCE|cairo.rd/OPERATOR_SOURCE>))
  * ((<Cairo::OPERATOR_XOR|cairo.rd/OPERATOR_XOR>))
  * ((<Cairo::PATH_CLOSE_PATH|cairo.rd/PATH_CLOSE_PATH>))
  * ((<Cairo::PATH_CURVE_TO|cairo.rd/PATH_CURVE_TO>))
  * ((<Cairo::PATH_LINE_TO|cairo.rd/PATH_LINE_TO>))
  * ((<Cairo::PATH_MOVE_TO|cairo.rd/PATH_MOVE_TO>))
  * ((<Cairo::PATTERN_TYPE_LINEAR|cairo.rd/PATTERN_TYPE_LINEAR>))
  * ((<Cairo::PATTERN_TYPE_RADIAL|cairo.rd/PATTERN_TYPE_RADIAL>))
  * ((<Cairo::PATTERN_TYPE_SOLID|cairo.rd/PATTERN_TYPE_SOLID>))
  * ((<Cairo::PATTERN_TYPE_SURFACE|cairo.rd/PATTERN_TYPE_SURFACE>))
  * ((<Cairo::SUBPIXEL_ORDER_BGR|cairo.rd/SUBPIXEL_ORDER_BGR>))
  * ((<Cairo::SUBPIXEL_ORDER_DEFAULT|cairo.rd/SUBPIXEL_ORDER_DEFAULT>))
  * ((<Cairo::SUBPIXEL_ORDER_RGB|cairo.rd/SUBPIXEL_ORDER_RGB>))
  * ((<Cairo::SUBPIXEL_ORDER_VBGR|cairo.rd/SUBPIXEL_ORDER_VBGR>))
  * ((<Cairo::SUBPIXEL_ORDER_VRGB|cairo.rd/SUBPIXEL_ORDER_VRGB>))
  * ((<Cairo::SURFACE_TYPE_BEOS|cairo.rd/SURFACE_TYPE_BEOS>))
  * ((<Cairo::SURFACE_TYPE_DIRECTFB|cairo.rd/SURFACE_TYPE_DIRECTFB>))
  * ((<Cairo::SURFACE_TYPE_GLITZ|cairo.rd/SURFACE_TYPE_GLITZ>))
  * ((<Cairo::SURFACE_TYPE_IMAGE|cairo.rd/SURFACE_TYPE_IMAGE>))
  * ((<Cairo::SURFACE_TYPE_PDF|cairo.rd/SURFACE_TYPE_PDF>))
  * ((<Cairo::SURFACE_TYPE_PS|cairo.rd/SURFACE_TYPE_PS>))
  * ((<Cairo::SURFACE_TYPE_QUARTZ|cairo.rd/SURFACE_TYPE_QUARTZ>))
  * ((<Cairo::SURFACE_TYPE_SVG|cairo.rd/SURFACE_TYPE_SVG>))
  * ((<Cairo::SURFACE_TYPE_WIN32|cairo.rd/SURFACE_TYPE_WIN32>))
  * ((<Cairo::SURFACE_TYPE_XCB|cairo.rd/SURFACE_TYPE_XCB>))
  * ((<Cairo::SURFACE_TYPE_XLIB|cairo.rd/SURFACE_TYPE_XLIB>))
  * ((<Cairo::SVG_VERSION_1_1|cairo.rd/SVG_VERSION_1_1>))
  * ((<Cairo::SVG_VERSION_1_2|cairo.rd/SVG_VERSION_1_2>))
  * ((<Cairo::VERSION|cairo.rd/VERSION>))
  * ((<Cairo.bindings_version|cairo.rd/Cairo.bindings_version>))
  * ((<Cairo::Context|cairo-context.rd/class Cairo::Context>))
  * ((<Cairo::Context.new|cairo-context.rd/Cairo::Context.new>))
  * ((<Cairo::Context#antialias|cairo-context.rd/antialias>))
  * ((<Cairo::Context#antialias=|cairo-context.rd/antialias=>))
  * ((<Cairo::Context#append_path|cairo-context.rd/append_path>))
  * ((<Cairo::Context#arc|cairo-context.rd/arc>))
  * ((<Cairo::Context#arc_negative|cairo-context.rd/arc_negative>))
  * ((<Cairo::Context#clip|cairo-context.rd/clip>))
  * ((<Cairo::Context#clip_preserve|cairo-context.rd/clip_preserve>))
  * ((<Cairo::Context#close_path|cairo-context.rd/close_path>))
  * ((<Cairo::Context#copy_page|cairo-context.rd/copy_page>))
  * ((<Cairo::Context#copy_path|cairo-context.rd/copy_path>))
  * ((<Cairo::Context#copy_path_flat|cairo-context.rd/copy_path_flat>))
  * ((<Cairo::Context#current_point|cairo-context.rd/current_point>))
  * ((<Cairo::Context#curve_to|cairo-context.rd/curve_to>))
  * ((<Cairo::Context#device_to_user|cairo-context.rd/device_to_user>))
  * ((<Cairo::Context#device_to_user_distance|cairo-context.rd/device_to_user_distance>))
  * ((<Cairo::Context#fill|cairo-context.rd/fill>))
  * ((<Cairo::Context#fill_extents|cairo-context.rd/fill_extents>))
  * ((<Cairo::Context#fill_preserve|cairo-context.rd/fill_preserve>))
  * ((<Cairo::Context#fill_rule|cairo-context.rd/fill_rule>))
  * ((<Cairo::Context#fill_rule=|cairo-context.rd/fill_rule=>))
  * ((<Cairo::Context#font_extents|cairo-context.rd/font_extents>))
  * ((<Cairo::Context#font_face|cairo-context.rd/font_face>))
  * ((<Cairo::Context#font_face=|cairo-context.rd/font_face=>))
  * ((<Cairo::Context#font_matrix|cairo-context.rd/font_matrix>))
  * ((<Cairo::Context#font_matrix=|cairo-context.rd/font_matrix=>))
  * ((<Cairo::Context#font_options|cairo-context.rd/font_options>))
  * ((<Cairo::Context#font_options=|cairo-context.rd/font_options=>))
  * ((<Cairo::Context#font_size=|cairo-context.rd/font_size=>))
  * ((<Cairo::Context#glyph_extents|cairo-context.rd/glyph_extents>))
  * ((<Cairo::Context#glyph_path|cairo-context.rd/glyph_path>))
  * ((<Cairo::Context#group_target|cairo-context.rd/group_target>))
  * ((<Cairo::Context#identity_matrix|cairo-context.rd/identity_matrix>))
  * ((<Cairo::Context#in_fill?|cairo-context.rd/in_fill?>))
  * ((<Cairo::Context#in_stroke?|cairo-context.rd/in_stroke?>))
  * ((<Cairo::Context#line_cap|cairo-context.rd/line_cap>))
  * ((<Cairo::Context#line_cap=|cairo-context.rd/line_cap=>))
  * ((<Cairo::Context#line_join|cairo-context.rd/line_join>))
  * ((<Cairo::Context#line_join=|cairo-context.rd/line_join=>))
  * ((<Cairo::Context#line_to|cairo-context.rd/line_to>))
  * ((<Cairo::Context#line_width|cairo-context.rd/line_width>))
  * ((<Cairo::Context#line_width=|cairo-context.rd/line_width=>))
  * ((<Cairo::Context#mask|cairo-context.rd/mask>))
  * ((<Cairo::Context#matrix|cairo-context.rd/matrix>))
  * ((<Cairo::Context#matrix=|cairo-context.rd/matrix=>))
  * ((<Cairo::Context#miter_limit|cairo-context.rd/miter_limit>))
  * ((<Cairo::Context#miter_limit=|cairo-context.rd/miter_limit=>))
  * ((<Cairo::Context#move_to|cairo-context.rd/move_to>))
  * ((<Cairo::Context#new_path|cairo-context.rd/new_path>))
  * ((<Cairo::Context#new_sub_path|cairo-context.rd/new_sub_path>))
  * ((<Cairo::Context#operator|cairo-context.rd/operator>))
  * ((<Cairo::Context#operator=|cairo-context.rd/operator=>))
  * ((<Cairo::Context#paint|cairo-context.rd/paint>))
  * ((<Cairo::Context#pop_group|cairo-context.rd/pop_group>))
  * ((<Cairo::Context#pop_group_to_source|cairo-context.rd/pop_group_to_source>))
  * ((<Cairo::Context#push_group|cairo-context.rd/push_group>))
  * ((<Cairo::Context#rectangle|cairo-context.rd/rectangle>))
  * ((<Cairo::Context#rel_curve_to|cairo-context.rd/rel_curve_to>))
  * ((<Cairo::Context#rel_line_to|cairo-context.rd/rel_line_to>))
  * ((<Cairo::Context#rel_move_to|cairo-context.rd/rel_move_to>))
  * ((<Cairo::Context#reset_clip|cairo-context.rd/reset_clip>))
  * ((<Cairo::Context#restore|cairo-context.rd/restore>))
  * ((<Cairo::Context#rotate|cairo-context.rd/rotate>))
  * ((<Cairo::Context#save|cairo-context.rd/save>))
  * ((<Cairo::Context#scale|cairo-context.rd/scale>))
  * ((<Cairo::Context#scaled_font=|cairo-context.rd/scaled_font=>))
  * ((<Cairo::Context#select_font_face|cairo-context.rd/select_font_face>))
  * ((<Cairo::Context#set_antialias|cairo-context.rd/set_antialias>))
  * ((<Cairo::Context#set_dash|cairo-context.rd/set_dash>))
  * ((<Cairo::Context#set_fill_rule|cairo-context.rd/set_fill_rule>))
  * ((<Cairo::Context#set_font_face|cairo-context.rd/set_font_face>))
  * ((<Cairo::Context#set_font_matrix|cairo-context.rd/set_font_matrix>))
  * ((<Cairo::Context#set_font_options|cairo-context.rd/set_font_options>))
  * ((<Cairo::Context#set_font_size|cairo-context.rd/set_font_size>))
  * ((<Cairo::Context#set_line_cap|cairo-context.rd/set_line_cap>))
  * ((<Cairo::Context#set_line_join|cairo-context.rd/set_line_join>))
  * ((<Cairo::Context#set_line_width|cairo-context.rd/set_line_width>))
  * ((<Cairo::Context#set_matrix|cairo-context.rd/set_matrix>))
  * ((<Cairo::Context#set_miter_limit|cairo-context.rd/set_miter_limit>))
  * ((<Cairo::Context#set_operator|cairo-context.rd/set_operator>))
  * ((<Cairo::Context#set_scaled_font|cairo-context.rd/set_scaled_font>))
  * ((<Cairo::Context#set_source|cairo-context.rd/set_source>))
  * ((<Cairo::Context#set_source_rgb|cairo-context.rd/set_source_rgb>))
  * ((<Cairo::Context#set_source_rgba|cairo-context.rd/set_source_rgba>))
  * ((<Cairo::Context#set_tolerance|cairo-context.rd/set_tolerance>))
  * ((<Cairo::Context#show_glyphs|cairo-context.rd/show_glyphs>))
  * ((<Cairo::Context#show_page|cairo-context.rd/show_page>))
  * ((<Cairo::Context#show_text|cairo-context.rd/show_text>))
  * ((<Cairo::Context#source|cairo-context.rd/source>))
  * ((<Cairo::Context#stroke|cairo-context.rd/stroke>))
  * ((<Cairo::Context#stroke_extents|cairo-context.rd/stroke_extents>))
  * ((<Cairo::Context#stroke_preserve|cairo-context.rd/stroke_preserve>))
  * ((<Cairo::Context#target|cairo-context.rd/target>))
  * ((<Cairo::Context#text_extents|cairo-context.rd/text_extents>))
  * ((<Cairo::Context#text_path|cairo-context.rd/text_path>))
  * ((<Cairo::Context#tolerance|cairo-context.rd/tolerance>))
  * ((<Cairo::Context#tolerance=|cairo-context.rd/tolerance=>))
  * ((<Cairo::Context#transform|cairo-context.rd/transform>))
  * ((<Cairo::Context#translate|cairo-context.rd/translate>))
  * ((<Cairo::Context#user_to_device|cairo-context.rd/user_to_device>))
  * ((<Cairo::Context#user_to_device_distance|cairo-context.rd/user_to_device_distance>))
  * ((<Cairo::Context::Circle|cairo-context-circle.rd/module Cairo::Context::Circle>))
  * ((<Cairo::Context::Circle#circle|cairo-context-circle.rd/circle>))
  * ((<Cairo::Context::Path|cairo-context-path.rd/module Cairo::Context::Path>))
  * ((<Cairo::Context::Path#map_path_onto|cairo-context-path.rd/map_path_onto>))
  * ((<Cairo::Context::Path#transform_path|cairo-context-path.rd/transform_path>))
  * ((<Cairo::Context::Path::Point|cairo-context-path-point.rd/module Cairo::Context::Path::Point>))
  * ((<Cairo::Context::Path::Point.distance|cairo-context-path-point.rd/Cairo::Context::Path::Point.distance>))
  * ((<Cairo::Context::Quad|cairo-context-quad.rd/module Cairo::Context::Quad>))
  * ((<Cairo::Context::Quad#quad_to|cairo-context-quad.rd/quad_to>))
  * ((<Cairo::Context::Quad#rel_quad_to|cairo-context-quad.rd/rel_quad_to>))
  * ((<Cairo::Context::Rectangle|cairo-context-rectangle.rd/module Cairo::Context::Rectangle>))
  * ((<Cairo::Context::Rectangle#rounded_rectangle|cairo-context-rectangle.rd/rounded_rectangle>))
  * ((<Cairo::Error|cairo-error.rd/class Cairo::Error>))
  * ((<Cairo::FileNotFound|cairo-file-not-found.rd/class Cairo::FileNotFound>))
  * ((<Cairo::FontExtents|cairo-font-extents.rd/class Cairo::FontExtents>))
  * ((<Cairo::FontExtents#ascent|cairo-font-extents.rd/ascent>))
  * ((<Cairo::FontExtents#descent|cairo-font-extents.rd/descent>))
  * ((<Cairo::FontExtents#height|cairo-font-extents.rd/height>))
  * ((<Cairo::FontExtents#max_x_advance|cairo-font-extents.rd/max_x_advance>))
  * ((<Cairo::FontExtents#max_y_advance|cairo-font-extents.rd/max_y_advance>))
  * ((<Cairo::FontExtents#to_s|cairo-font-extents.rd/to_s>))
  * ((<Cairo::FontFace|cairo-font-face.rd/class Cairo::FontFace>))
  * ((<Cairo::FontFace#type|cairo-font-face.rd/type>))
  * ((<Cairo::FontOptions|cairo-font-options.rd/class Cairo::FontOptions>))
  * ((<Cairo::FontOptions.new|cairo-font-options.rd/Cairo::FontOptions.new>))
  * ((<Cairo::FontOptions#antialias|cairo-font-options.rd/antialias>))
  * ((<Cairo::FontOptions#antialias=|cairo-font-options.rd/antialias=>))
  * ((<Cairo::FontOptions#dup|cairo-font-options.rd/dup>))
  * ((<Cairo::FontOptions#eql?|cairo-font-options.rd/eql?>))
  * ((<Cairo::FontOptions#hash|cairo-font-options.rd/hash>))
  * ((<Cairo::FontOptions#hint_metrics|cairo-font-options.rd/hint_metrics>))
  * ((<Cairo::FontOptions#hint_metrics=|cairo-font-options.rd/hint_metrics=>))
  * ((<Cairo::FontOptions#hint_style|cairo-font-options.rd/hint_style>))
  * ((<Cairo::FontOptions#hint_style=|cairo-font-options.rd/hint_style=>))
  * ((<Cairo::FontOptions#merge|cairo-font-options.rd/merge>))
  * ((<Cairo::FontOptions#set_antialias|cairo-font-options.rd/set_antialias>))
  * ((<Cairo::FontOptions#set_hint_metrics|cairo-font-options.rd/set_hint_metrics>))
  * ((<Cairo::FontOptions#set_hint_style|cairo-font-options.rd/set_hint_style>))
  * ((<Cairo::FontOptions#set_subpixel_order|cairo-font-options.rd/set_subpixel_order>))
  * ((<Cairo::FontOptions#subpixel_order|cairo-font-options.rd/subpixel_order>))
  * ((<Cairo::FontOptions#subpixel_order=|cairo-font-options.rd/subpixel_order=>))
  * ((<Cairo::Glyph|cairo-glyph.rd/class Cairo::Glyph>))
  * ((<Cairo::Glyph.new|cairo-glyph.rd/Cairo::Glyph.new>))
  * ((<Cairo::Glyph#index|cairo-glyph.rd/index>))
  * ((<Cairo::Glyph#index=|cairo-glyph.rd/index=>))
  * ((<Cairo::Glyph#set_index|cairo-glyph.rd/set_index>))
  * ((<Cairo::Glyph#set_x|cairo-glyph.rd/set_x>))
  * ((<Cairo::Glyph#set_y|cairo-glyph.rd/set_y>))
  * ((<Cairo::Glyph#to_s|cairo-glyph.rd/to_s>))
  * ((<Cairo::Glyph#x|cairo-glyph.rd/x>))
  * ((<Cairo::Glyph#x=|cairo-glyph.rd/x=>))
  * ((<Cairo::Glyph#y|cairo-glyph.rd/y>))
  * ((<Cairo::Glyph#y=|cairo-glyph.rd/y=>))
  * ((<Cairo::GradientPattern|cairo-gradient-pattern.rd/class Cairo::GradientPattern>))
  * ((<Cairo::GradientPattern#add_color_stop|cairo-gradient-pattern.rd/add_color_stop>))
  * ((<Cairo::GradientPattern#add_color_stop_rgb|cairo-gradient-pattern.rd/add_color_stop_rgb>))
  * ((<Cairo::GradientPattern#add_color_stop_rgba|cairo-gradient-pattern.rd/add_color_stop_rgba>))
  * ((<Cairo::ImageSurface|cairo-image-surface.rd/class Cairo::ImageSurface>))
  * ((<Cairo::ImageSurface.from_png|cairo-image-surface.rd/Cairo::ImageSurface.from_png>))
  * ((<Cairo::ImageSurface.new|cairo-image-surface.rd/Cairo::ImageSurface.new>))
  * ((<Cairo::ImageSurface#data|cairo-image-surface.rd/data>))
  * ((<Cairo::ImageSurface#format|cairo-image-surface.rd/format>))
  * ((<Cairo::ImageSurface#height|cairo-image-surface.rd/height>))
  * ((<Cairo::ImageSurface#stride|cairo-image-surface.rd/stride>))
  * ((<Cairo::ImageSurface#width|cairo-image-surface.rd/width>))
  * ((<Cairo::InvalidContentError|cairo-invalid-content-error.rd/class Cairo::InvalidContentError>))
  * ((<Cairo::InvalidDashError|cairo-invalid-dash-error.rd/class Cairo::InvalidDashError>))
  * ((<Cairo::InvalidDscCommentError|cairo-invalid-dsc-comment-error.rd/class Cairo::InvalidDscCommentError>))
  * ((<Cairo::InvalidFormatError|cairo-invalid-format-error.rd/class Cairo::InvalidFormatError>))
  * ((<Cairo::InvalidMatrixError|cairo-invalid-matrix-error.rd/class Cairo::InvalidMatrixError>))
  * ((<Cairo::InvalidPathDataError|cairo-invalid-path-data-error.rd/class Cairo::InvalidPathDataError>))
  * ((<Cairo::InvalidPopGroupError|cairo-invalid-pop-group-error.rd/class Cairo::InvalidPopGroupError>))
  * ((<Cairo::InvalidRestoreError|cairo-invalid-restore-error.rd/class Cairo::InvalidRestoreError>))
  * ((<Cairo::InvalidStatusError|cairo-invalid-status-error.rd/class Cairo::InvalidStatusError>))
  * ((<Cairo::InvalidStringError|cairo-invalid-string-error.rd/class Cairo::InvalidStringError>))
  * ((<Cairo::InvalidVisualError|cairo-invalid-visual-error.rd/class Cairo::InvalidVisualError>))
  * ((<Cairo::LinearPattern|cairo-linear-pattern.rd/class Cairo::LinearPattern>))
  * ((<Cairo::LinearPattern.new|cairo-linear-pattern.rd/Cairo::LinearPattern.new>))
  * ((<Cairo::Matrix|cairo-matrix.rd/class Cairo::Matrix>))
  * ((<Cairo::Matrix.identity|cairo-matrix.rd/Cairo::Matrix.identity>))
  * ((<Cairo::Matrix.new|cairo-matrix.rd/Cairo::Matrix.new>))
  * ((<Cairo::Matrix.rotate|cairo-matrix.rd/Cairo::Matrix.rotate>))
  * ((<Cairo::Matrix.scale|cairo-matrix.rd/Cairo::Matrix.scale>))
  * ((<Cairo::Matrix.translate|cairo-matrix.rd/Cairo::Matrix.translate>))
  * ((<Cairo::Matrix#*|cairo-matrix.rd/*>))
  * ((<Cairo::Matrix#clone|cairo-matrix.rd/clone>))
  * ((<Cairo::Matrix#dup|cairo-matrix.rd/dup>))
  * ((<Cairo::Matrix#identity!|cairo-matrix.rd/identity!>))
  * ((<Cairo::Matrix#invert|cairo-matrix.rd/invert>))
  * ((<Cairo::Matrix#invert!|cairo-matrix.rd/invert!>))
  * ((<Cairo::Matrix#matrix_distance|cairo-matrix.rd/matrix_distance>))
  * ((<Cairo::Matrix#multiply|cairo-matrix.rd/multiply>))
  * ((<Cairo::Matrix#multiply!|cairo-matrix.rd/multiply!>))
  * ((<Cairo::Matrix#rotate|cairo-matrix.rd/rotate>))
  * ((<Cairo::Matrix#rotate!|cairo-matrix.rd/rotate!>))
  * ((<Cairo::Matrix#scale|cairo-matrix.rd/scale>))
  * ((<Cairo::Matrix#scale!|cairo-matrix.rd/scale!>))
  * ((<Cairo::Matrix#set|cairo-matrix.rd/set>))
  * ((<Cairo::Matrix#to_a|cairo-matrix.rd/to_a>))
  * ((<Cairo::Matrix#to_s|cairo-matrix.rd/to_s>))
  * ((<Cairo::Matrix#transform_point|cairo-matrix.rd/transform_point>))
  * ((<Cairo::Matrix#translate|cairo-matrix.rd/translate>))
  * ((<Cairo::Matrix#translate!|cairo-matrix.rd/translate!>))
  * ((<Cairo::NoCurrentPointError|cairo-no-current-point-error.rd/class Cairo::NoCurrentPointError>))
  * ((<Cairo::NullPointerError|cairo-null-pointer-error.rd/class Cairo::NullPointerError>))
  * ((<Cairo::PDFSurface|cairo-pdf-surface.rd/class Cairo::PDFSurface>))
  * ((<Cairo::PDFSurface.new|cairo-pdf-surface.rd/Cairo::PDFSurface.new>))
  * ((<Cairo::PDFSurface#set_size|cairo-pdf-surface.rd/set_size>))
  * ((<Cairo::PSSurface|cairo-ps-surface.rd/class Cairo::PSSurface>))
  * ((<Cairo::PSSurface.new|cairo-ps-surface.rd/Cairo::PSSurface.new>))
  * ((<Cairo::PSSurface#dsc_begin_page_setup|cairo-ps-surface.rd/dsc_begin_page_setup>))
  * ((<Cairo::PSSurface#dsc_begin_setup|cairo-ps-surface.rd/dsc_begin_setup>))
  * ((<Cairo::PSSurface#dsc_comment|cairo-ps-surface.rd/dsc_comment>))
  * ((<Cairo::PSSurface#set_size|cairo-ps-surface.rd/set_size>))
  * ((<Cairo::Path|cairo-path.rd/class Cairo::Path>))
  * ((<Cairo::Path#each|cairo-path.rd/each>))
  * ((<Cairo::Pattern|cairo-pattern.rd/class Cairo::Pattern>))
  * ((<Cairo::Pattern.new|cairo-pattern.rd/Cairo::Pattern.new>))
  * ((<Cairo::Pattern#__extend__|cairo-pattern.rd/__extend__>))
  * ((<Cairo::Pattern#extend|cairo-pattern.rd/extend>))
  * ((<Cairo::Pattern#extend=|cairo-pattern.rd/extend=>))
  * ((<Cairo::Pattern#filter|cairo-pattern.rd/filter>))
  * ((<Cairo::Pattern#filter=|cairo-pattern.rd/filter=>))
  * ((<Cairo::Pattern#matrix|cairo-pattern.rd/matrix>))
  * ((<Cairo::Pattern#matrix=|cairo-pattern.rd/matrix=>))
  * ((<Cairo::Pattern#set_extend|cairo-pattern.rd/set_extend>))
  * ((<Cairo::Pattern#set_filter|cairo-pattern.rd/set_filter>))
  * ((<Cairo::Pattern#set_matrix|cairo-pattern.rd/set_matrix>))
  * ((<Cairo::Pattern#type|cairo-pattern.rd/type>))
  * ((<Cairo::PatternTypeMismatchError|cairo-pattern-type-mismatch-error.rd/class Cairo::PatternTypeMismatchError>))
  * ((<Cairo::RadialPattern|cairo-radial-pattern.rd/class Cairo::RadialPattern>))
  * ((<Cairo::RadialPattern.new|cairo-radial-pattern.rd/Cairo::RadialPattern.new>))
  * ((<Cairo::ReadError|cairo-read-error.rd/class Cairo::ReadError>))
  * ((<Cairo::SVGSurface|cairo-svg-surface.rd/class Cairo::SVGSurface>))
  * ((<Cairo::SVGSurface::VERSION_1_1|cairo-svg-surface.rd/VERSION_1_1>))
  * ((<Cairo::SVGSurface::VERSION_1_2|cairo-svg-surface.rd/VERSION_1_2>))
  * ((<Cairo::SVGSurface.new|cairo-svg-surface.rd/Cairo::SVGSurface.new>))
  * ((<Cairo::SVGSurface.version_to_string|cairo-svg-surface.rd/Cairo::SVGSurface.version_to_string>))
  * ((<Cairo::SVGSurface.versions|cairo-svg-surface.rd/Cairo::SVGSurface.versions>))
  * ((<Cairo::SVGSurface.versions_as_string|cairo-svg-surface.rd/Cairo::SVGSurface.versions_as_string>))
  * ((<Cairo::SVGSurface#restrict_to_version|cairo-svg-surface.rd/restrict_to_version>))
  * ((<Cairo::ScaledFont|cairo-scaled-font.rd/class Cairo::ScaledFont>))
  * ((<Cairo::ScaledFont.new|cairo-scaled-font.rd/Cairo::ScaledFont.new>))
  * ((<Cairo::ScaledFont#ctm|cairo-scaled-font.rd/ctm>))
  * ((<Cairo::ScaledFont#extents|cairo-scaled-font.rd/extents>))
  * ((<Cairo::ScaledFont#font_face|cairo-scaled-font.rd/font_face>))
  * ((<Cairo::ScaledFont#font_matrix|cairo-scaled-font.rd/font_matrix>))
  * ((<Cairo::ScaledFont#font_options|cairo-scaled-font.rd/font_options>))
  * ((<Cairo::ScaledFont#glyph_extents|cairo-scaled-font.rd/glyph_extents>))
  * ((<Cairo::ScaledFont#text_extents|cairo-scaled-font.rd/text_extents>))
  * ((<Cairo::ScaledFont#type|cairo-scaled-font.rd/type>))
  * ((<Cairo::SolidPattern|cairo-solid-pattern.rd/class Cairo::SolidPattern>))
  * ((<Cairo::SolidPattern.new|cairo-solid-pattern.rd/Cairo::SolidPattern.new>))
  * ((<Cairo::Surface|cairo-surface.rd/class Cairo::Surface>))
  * ((<Cairo::Surface#clone|cairo-surface.rd/clone>))
  * ((<Cairo::Surface#content|cairo-surface.rd/content>))
  * ((<Cairo::Surface#create_similar|cairo-surface.rd/create_similar>))
  * ((<Cairo::Surface#device_offset|cairo-surface.rd/device_offset>))
  * ((<Cairo::Surface#dup|cairo-surface.rd/dup>))
  * ((<Cairo::Surface#finish|cairo-surface.rd/finish>))
  * ((<Cairo::Surface#flush|cairo-surface.rd/flush>))
  * ((<Cairo::Surface#font_options|cairo-surface.rd/font_options>))
  * ((<Cairo::Surface#mark_dirty|cairo-surface.rd/mark_dirty>))
  * ((<Cairo::Surface#set_device_offset|cairo-surface.rd/set_device_offset>))
  * ((<Cairo::Surface#set_fallback_resolution|cairo-surface.rd/set_fallback_resolution>))
  * ((<Cairo::Surface#type|cairo-surface.rd/type>))
  * ((<Cairo::Surface#write_to_png|cairo-surface.rd/write_to_png>))
  * ((<Cairo::SurfaceFinishedError|cairo-surface-finished-error.rd/class Cairo::SurfaceFinishedError>))
  * ((<Cairo::SurfacePattern|cairo-surface-pattern.rd/class Cairo::SurfacePattern>))
  * ((<Cairo::SurfacePattern.new|cairo-surface-pattern.rd/Cairo::SurfacePattern.new>))
  * ((<Cairo::SurfaceTypeMismatchError|cairo-surface-type-mismatch-error.rd/class Cairo::SurfaceTypeMismatchError>))
  * ((<Cairo::TextExtents|cairo-text-extents.rd/class Cairo::TextExtents>))
  * ((<Cairo::TextExtents#height|cairo-text-extents.rd/height>))
  * ((<Cairo::TextExtents#to_s|cairo-text-extents.rd/to_s>))
  * ((<Cairo::TextExtents#width|cairo-text-extents.rd/width>))
  * ((<Cairo::TextExtents#x_advance|cairo-text-extents.rd/x_advance>))
  * ((<Cairo::TextExtents#x_bearing|cairo-text-extents.rd/x_bearing>))
  * ((<Cairo::TextExtents#y_advance|cairo-text-extents.rd/y_advance>))
  * ((<Cairo::TextExtents#y_bearing|cairo-text-extents.rd/y_bearing>))
  * ((<Cairo::WriteError|cairo-write-error.rd/class Cairo::WriteError>))
